### ISSUE TITLE
proposal: unique identifier for holiday

### ISSUE THREAD

**Issue by jamesdixon** [commenthol/date-holidays#10]
Hi again,

I wanted to run something by you to see what you thought or if you have a better solution.

In my use case, I need to be able to automatically apply holiday surcharges to appointments that fall on a holiday. Each business has a list of observed holidays, so when a customer schedules an appointment, I first need to check to see if the business observes the holiday and if they do, then check to ensure the date of the appointment falls on the holiday. For the first part, I'm currently matching a list of holiday names to what's output by the `getHolidays(year)` function of your library. This works great, but I'd prefer to match on some unique identifier rather than a language-dependent name.

Would you be open to adding unique identifiers for holidays that would be the same regardless of language? Do you have a better solution that I may be missing?

Thanks!

**Comment by commenthol** [comment]
The holiday names for all countries are indeed unique. So the name is the identifier. To lookup the data you can just restrict all names to be in english, using `new Holidays(country, {languages: ['en']})`. Usually all countries should have an english name as fallback.

**Comment by jamesdixon** [comment]
Agreed that it works, but I feel that a numeric id or something similar is probably a safer bet and a bit lighter from a data perspective. 

That said, not a big deal, but wanted to throw it out there.

Great work on this library 👍

**Comment by commenthol** [comment]
Due to reasons of extra efforts of constantly maintaining those proposed Ids I am closing this Issue.

**Comment by jamesdixon** [comment]
Hello! I realize this is an old issue that I had brought up years ago but wanted to give a heads up that this particular issue came back to bite me. I've been relying on names to identify holidays but after making an update to the library, some dates stopped working because the name was changed.

Any chance you'd consider this now? I don't have a 100% insight into the process but using a UUID as a unique identifier would work swimmingly.

**Comment by gerryster** [comment]
Hey @jamesdixon , I also have a similar use case in that I store the holidays produced by this Node Module in a database table. I have handled this situation by only importing one holiday per date. I had considered something more complex but settled on this. With that said, this is still imperfect as a date for a holiday can change; often times by a formal government declaration.

The difficulty as @commenthol previously said is maintaining the identifiers. Also, how does one uniquely identify a holiday? This seems simple on the surface. For example, Christmas is always Christmas. However, things get more tricky as holidays evolve over time. For example, in 2017 in Alaska, the 2nd Monday in November changed from being Columbus Day to Indigenous Peoples' Day. Are these the same holiday? Sure they share the same rule for when it occurs but they are clearly celebrating two different things.

**Comment by jamesdixon** [comment]
@gerryster thanks for the reply! Storing these holidays in your own table is definitely a workable solution, but just as my system, imperfect as you suggest.

> The difficulty as @commenthol previously said is maintaining the identifiers. Also, how does one uniquely identify a holiday? This seems simple on the surface. For example, Christmas is always Christmas. However, things get more tricky as holidays evolve over time. For example, in 2017 in Alaska, the 2nd Monday in November changed from being Columbus Day to Indigenous Peoples' Day. Are these the same holiday? Sure they share the same rule for when it occurs but they are clearly celebrating two different things.

Great question. I would imagine a unique identifier for each holiday in each locale. So Christmas in the US would have a different identifier than Christmas in the UK. 

In your example of Alaska and Columbus Day vs. Indigenous People's Day, to me, that has nothing to do with an actual unique identifier. That's a decision on the library's part whether they want to go by the official ruling and change the "Columbus Day" entry to "Indigenous People's Day" or keep it as two separate holidays. If the former, it would still have the same unique identifier. If the latter, Columbus Day would still have the same unique identifier and the newly minted Indigenous People's Day would get its own. Ultimately, it's up to the consuming application to determine what they prefer to display.

If I'm missing something, I apologize but I took @commenthol's comment regarding maintenance to mean something different.
