### ISSUE TITLE
Suggestion: create a folder with a "holiday dates" json file for each region

### ISSUE THREAD

**Issue by aavmurphy** [commenthol/date-holidays#100]
have a 'distribution' json directory of holiday dates, 
i.e. json only, no code
e.g, so i can just pick up `/dates/GB/England-Wales.json` or `/dates/GB/GB.json` from the CDN or npm ....
=> its programming language independent
=> its very small (most people will just need 1 or 2 small files with a handful of dates (their country and possibly, region)
=> have 2 option, an, 'array of dates => name' file, and an 'object of names => date' file, so people can choose what they need.

**Comment by commenthol** [comment]
you already can set up a custom build in your project. See the custom build section in the Readme.

**Comment by aavmurphy** [comment]
but you'd have to use npm & node?
with my suggestion, anyone can use it as a service, just by fetching a url

**Comment by olragon** [comment]
@aavmurphy checkout [date-holidays-data](https://github.com/olragon/date-holidays-data)
