### ISSUE TITLE
isHoliday function doesn't work

### ISSUE THREAD

**Issue by steeveAtAndjaro** [commenthol/date-holidays#102]
Hello,

I tried to use one of the readme example but I got an error 

date-holidays installed : 1.4.0
chrome : 74.0.3729.169

My code ( in a react component):
`var hd = new Holidays( 'FR' );`

// working
`console.log( hd.getHolidays() );`

// Uncaught TypeError: Cannot read property 'fn' of undefined
`hd.isHoliday( new Date( '2016-02-09 00:00:00 GMT+0000' ) ) `

Did I forget . to init something  ?

**Comment by commenthol** [comment]
If running your lines with node all is ok. So the problem might be related to your project setup.

**Comment by commenthol** [comment]
Hi @steeveAtAndjaro, I am closing your issue. Please reopen if the issue still persists while giving us some more insights. Thanks.
