### ISSUE TITLE
examples/browser typo for index.html javascript resource

### ISSUE THREAD

**Issue by dainius-s** [commenthol/date-holidays#111]
there is a typo in index.html file

on line 36 includes javascript file "index.js" when in fact it's "test.js"

current
`<script src="index.js" type="text/javascript"></script>`

should be 
`<script src="test.js" type="text/javascript"></script>`

**Comment by commenthol** [comment]
Hi @dainius-s ,
`index.js` is generated with browserify but not committed. You'll need to check out the project and run `npm run build`. The built version is on https://commenthol.github.io/date-holidays/
