### ISSUE TITLE
Clarify Canada mandatory public holidays

### ISSUE THREAD

**Issue by Suisse00** [commenthol/date-holidays#114]
Hi, I'm from the Quebec state of Canada and I do know the "Boxing Day" (December 26th) and Remembrance Day (November 11) ARENT official holidays (as stated in by my state http://www4.gouv.qc.ca/fr/Portail/citoyens/programme-service/Pages/Info.aspx?sqctype=sujet&sqcid=329 - thought December 25th is usually paid by the employer).
There is no trace of a possible weird exception for the Quebec state. (Though I did only a quick search)

When looking for the Canada holidays I found a [couple](https://www.canada.ca/en/employment-social-development/programs/employment-standards/holidays.html) of [links](https://www.canada.ca/en/employment-social-development/services/labour-standards/reports/holidays.html#h2.2), even on the Canada tax web portal I found 2 pages (https://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/services-paye-pay-services/paye-centre-pay/feries-holidays-eng.html and https://www.canada.ca/en/revenue-agency/services/tax/public-holidays.html), listing the Boxing Day as well as the Remembrance Day, as Canada holidays. One of these page refers to what looks like a [law page](https://laws-lois.justice.gc.ca/eng/acts/H-5/page-1.html#h-3). 
So I'm confused even as a Canadian...

Google embedded result tools also match my state website. (Warning: On April we have a substitution day)

I do believe they could be for employees working for the Canada government and aren't public holidays. 

I don't quite want to change my country file yet since I don't know per-state. If some github users from Canada could post here their holidays for their state it would be great!

**Comment by amoebaworks** [comment]
BC Family Day in 2020 is Feb 17. Your mapping is returning Feb 10. It changed in 2019 from 2nd Mon to 3rd Mon. Reference: https://www.statutoryholidays.com/bc.php

**Comment by commenthol** [comment]
@amoebaworks I would prepare a PR for BC Family Day. @Suisse00 for the above I would need guidance what and how days should be changed. It's currently a bit confusing to me.

**Comment by Suisse00** [comment]
Oh, I just found https://en.wikipedia.org/wiki/Public_holidays_in_Canada#Provincial_and_territorial_holidays (source: the @attrb from the .yaml... RTFM!) Seem right to me.
