### ISSUE TITLE
Fix UK bank holiday (Early May bank holiday (VE day))

### ISSUE THREAD

**Issue by SoftDev1987** [commenthol/date-holidays#122]
Currently, the May Bank holiday on this module is incorrect. It states that the May bank holiday is on the 4th of May, but it's on the 8th (https://www.gov.uk/bank-holidays). This would normally be correct but it's VE day. Could you fix this?

**Comment by commenthol** [comment]
@SoftDev1987 PR #123 is on the way. Could you please check if all is as expected?

**Comment by SoftDev1987** [comment]
Fixed - thanks! :)
