### ISSUE TITLE
Denmark is missing one holiday

### ISSUE THREAD

**Issue by phillipstemann** [commenthol/date-holidays#129]
Hi

Really great plugin. Though one day is missing from the list when I pull danish holidays.
It's 24th of dec. Christmas Eve in Denmark, it's a public holiday as well.

**Comment by commenthol** [comment]
Hi @phillipstemann, Could you please name us some source? In https://da.wikipedia.org/wiki/Danske_helligdage Christmas Eve is not listed as an public holiday. 
Is it a "bank" holiday? Do people work half day only?

**Comment by phillipstemann** [comment]
Hi
I'm danish, and 24th is a holiday. Everything is closed, and everyone is off work.

**Comment by commenthol** [comment]
Great. Would you mind setting the holiday type to `observance` then?

**Comment by commenthol** [comment]
Hi @phillipstemann,

Would you mind checking the following list for danish holidays? Added days are 1.maj, Juleaften, Nytårsaften. Thanks for your support.

```
  'Tue   2019-01-01 00:00:00   public       Nytår',
  'Mon   2019-03-04 00:00:00   observance   Fastelavn',
  'Thu   2019-04-18 00:00:00   public       Skærtorsdag',
  'Fri   2019-04-19 00:00:00   public       Langfredag',
  'Sun   2019-04-21 00:00:00   public       Påskesøndag',
  'Mon   2019-04-22 00:00:00   public       Anden påskedag',
  'Wed   2019-05-01 00:00:00   observance   1. maj',
  'Sun   2019-05-12 00:00:00   observance   Mors Dag',
  'Fri   2019-05-17 00:00:00   public       Store Bededag',
  'Thu   2019-05-30 00:00:00   public       Kristi Himmelfartsdag',
  'Wed   2019-06-05 00:00:00   observance   Grundlovsdag',
  'Sun   2019-06-09 00:00:00   public       Pinsedag',
  'Mon   2019-06-10 00:00:00   public       Anden Pinsedag',
  'Tue   2019-12-24 00:00:00   observance   Juleaften',
  'Wed   2019-12-25 00:00:00   public       Juledag',
  'Thu   2019-12-26 00:00:00   public       Anden Juledag',
  'Tue   2019-12-31 15:00:00   observance   Nytårsaften'
```

**Comment by phillipstemann** [comment]
Hi @commenthol 

I wouldn't add "Nytårsaften", the others you can add as observance.
Nytårsaften is a normal day in Denmark. Some has half of the day of, but it's very few.

**Comment by commenthol** [comment]
Nytårsaften is removed now. Thanks for your support.
