### ISSUE TITLE
Easter sunday and Pentacoste sunday are inconsistent in DE.

### ISSUE THREAD

**Issue by leipert** [commenthol/date-holidays#13]
The following problem is not fixed in #12. Do you think it is fix worthy?

Only DE-BB observes `easter` and `easter 49` as public holidays. ([source][1], easter sunday and pentecoste sunday are not marked bold)

[1]: https://de.wikipedia.org/w/index.php?title=Gesetzliche_Feiertage_in_Deutschland&oldid=165137747#.C3.9Cbersicht_aller_gesetzlichen_Feiertage

**Comment by commenthol** [comment]
IMHO this makes sense to fix this. In this case Easter and Pentecost should be of type `observance` for DE, but remain `public` for DE-bb. Thanks for rising.

**Comment by commenthol** [comment]
Fixed with PR #18
