### ISSUE TITLE
Public holiday missing from Bayern region in Germany

### ISSUE THREAD

**Issue by FarkasAndras93** [commenthol/date-holidays#134]
Based on this sites: 
https://www.studying-in-germany.org/public-holidays-germany/
https://www.expatica.com/de/about/culture-history/public-holidays-in-germany-and-important-german-holidays-2018-105411/
"Augsburger Friedensfest: holiday in individual regions (always on 08. Augugst)" - is missing from Bayern region in Germany.

**Comment by commenthol** [comment]
Hi, date-holidays is structured by country, state and region.
The "Augsburger Friedensfest" is a public holiday only for the area of the city of Augsburg but not for the whole state of Bavaria, such it is correctly attributed if choosing DE-BY-A .
