### ISSUE TITLE
Incorrect subdivision code? (BE-DE)

### ISSUE THREAD

**Issue by jbroudou** [commenthol/date-holidays#135]
The ISO subdivisions for Belgium are listed at https://en.wikipedia.org/wiki/ISO_3166-2:BE.

https://github.com/commenthol/date-holidays/blob/1e885a0d7950d1c0d898685e07d14e5dce9acfbd/data/countries/BE.yaml#L79 includes BE-DE (name: Deutschsprachige Gemeinschaft) as a subdivision of Belgium.

As the ISO list does not include BE-DE, can you please explain how BE-DE fits into the ISO subdivision schema for Belgium.

**Comment by commenthol** [comment]
Hi, to be honest I did not find a solution to map the different languages to the regions. If you are Belgium (what I suppose) I would appreciate to adapt to a ISO schema which reflects the regions and different languages better. Any PR is welcome.

**Comment by jbroudou** [comment]
Hi @commenthol `Deutschsprachige Gemeinschaft` isn't a recognised ISO subdivision, but I understand why you've included it here. All current subdivision codes for Belgium are 3 letter codes, so it is unlikely that 'BE' would clash with any future code changes.
