### ISSUE TITLE
Error: this._shorten is not a function

### ISSUE THREAD

**Issue by emiltout** [commenthol/date-holidays#136]
Hi there,

I'm trying to use date-holidays in my angular 7 project with typescript.
I meet an issue when I intialize new Holidays('US', 'la', 'no') (for exemple) : 

![image](https://user-images.githubusercontent.com/15676958/71978253-26855700-321b-11ea-8d77-7534889b95dc.png)

![image](https://user-images.githubusercontent.com/15676958/71971849-c2a76200-320b-11ea-9362-56f8d6d8948c.png)

It seems that the problem occurs when the country is made of 2 characters, I have the same problem with new Holidays('Fr'), but when i'm doing new Holidays('France') the result is : 

![image](https://user-images.githubusercontent.com/15676958/71977966-77e11680-321a-11ea-8a3a-71804c382a34.png)

Beside, when I use something like 
![image](https://user-images.githubusercontent.com/15676958/71977624-8e3aa280-3219-11ea-97f6-51575cd35cc9.png)
 it works fine.

My import is made as follow: 
![image](https://user-images.githubusercontent.com/15676958/71977483-2f752900-3219-11ea-8f9b-5b873adb7d83.png)

I think that there is something wrong with my init but i don't understand what.. I'm pretty new in the web development !
Thanks !

**Comment by commenthol** [comment]
Hi,
what is the reason to use 

    import * as Holidays from ...

instead of

    import Holidays from ...

?

**Comment by commenthol** [comment]
Closing
