### ISSUE TITLE
Lunar + Gregorian

### ISSUE THREAD

**Issue by beeing** [commenthol/date-holidays#140]
Hi, is there an option we can specify both Lunar and Gregorian?

This should solve dates such as Vesak "Full Moon in the month of May" as per https://www.un.org/en/events/vesakday/

Thanks in advance.

**Comment by beeing** [comment]
After testing the dates further, it looks like lunar itself is sufficient.

FYI, Vesak falls on 15th of 4th month in lunar.

**Comment by gerryster** [comment]
Vesak is defined pretty manually in Singapore (https://github.com/commenthol/date-holidays/blob/1e885a0d7950d1c0d898685e07d14e5dce9acfbd/data/countries/SG.yaml#L60-L103). If you have a more general way of defining it that would be helpful. Note that I am not sure if Singapore has some specific rules that other countries to not follow.

**Comment by beeing** [comment]
Here's what I'm testing out:

```yaml
      chinese 04-0-15:
        _name: Vesak
```

Also, found that it works for Deepavali too:

```yaml
      chinese 09-0-29:
        _name: Deepavali
```

Note: I've tested a few years but not a very extensive tests though.
