### ISSUE TITLE
Substitute holidays - both and single days

### ISSUE THREAD

**Issue by jbroudou** [commenthol/date-holidays#150]
In some locations when a holiday falls on a weekend, it is moved to a weekday as an observed day. In some of these locations only the observed day is considered a holiday whereas in others both the observed and original days are considered holidays. This is an important distinction in some jurisdictions. 

Is there any chance of supporting an additional flag against observed holidays that indicate the original day is or isn't a holiday?

**Comment by commenthol** [comment]
For both holidays you'd specify

```
03-02: 
  name: holiday
substitutes 03-02 if sunday then next monday:
  name: holiday
```

For a single holiday which is shifted you'd specify

```
03-02 if sunday then next monday:
  name: holiday
```

In case you like to add the type "observation" on 03-02 you may add:

```
03-02:
  name: holiday
  type: observance
03-02 if sunday then next monday:
  name: holiday
```
