### ISSUE TITLE
Add german school holidays

### ISSUE THREAD

**Issue by madmax75** [commenthol/date-holidays#167]
Is it possible to integrate the German school holidays ?

Example:
https://publicholidays.de/school-holidays/north-rhine-westphalia/

**Comment by commenthol** [comment]
Hi @madmax75 ,
No objections from my side. If you like to maintain these for Germany you help is much appreciated. The holiday type school is available as well as duration. E.g. for an imaginary two weeks holiday starting this week the rule could be "2020-08-31 P12D".
