### ISSUE TITLE
[Bug] 2020-03-19, 2020-04-09, 2020-12-07 are not National Holidays in Spain

### ISSUE THREAD

**Issue by alexfernandez** [commenthol/date-holidays#178]
The [data for Spain](https://github.com/commenthol/date-holidays/blob/master/data/countries/ES.yaml) states as a source the [wikipedia page](https://es.m.wikipedia.org/wiki/Calendario_laboral).

However this year St Joseph's day (March 19th, 2020-03-19) is not a national Holiday but a substitute day. The library returns:

```
{
  date: '2020-03-19 00:00:00',
  start: 2020-03-18T23:00:00.000Z,
  end: 2020-03-19T23:00:00.000Z,
  name: 'San José',
  type: 'public'
}
```

You can in fact look at the [official bulletin](https://www.boe.es/boe/dias/2019/10/11/pdfs/BOE-A-2019-14552.pdf) where 2020-03-19 is a substitute Holiday, and is therefore not official in some regions.

Something similar happens with 2020-04-09:

```
{
  date: '2020-04-09 00:00:00',
  start: 2020-04-08T22:00:00.000Z,
  end: 2020-04-09T22:00:00.000Z,
  name: 'Jueves Santo',
  type: 'public'
}
```

And with 2020-12-07:

```
{
  date: '2020-12-07 00:00:00',
  start: 2020-12-06T23:00:00.000Z,
  end: 2020-12-07T23:00:00.000Z,
  name: 'Día de la Constitución Española',
  type: 'public'
}
```

Note that, although 2020-01-06 is a substitute Holiday in the official document document, it has not been substituted in any region, so it is OK to list it as a national Holiday.

**Comment by commenthol** [comment]
Hi @alexfernandez,
Thanks for posting the issue. 
I am confused what to do now. Would you mind stating what are your expected changes?
E.g remove this, add this, change to this.
Please also consider opening a pull request.

**Comment by alexfernandez** [comment]
I will try to fix it and send a pull request :sweat_smile: 

Thanks!

**Comment by alexfernandez** [comment]
[Pull request](https://github.com/commenthol/date-holidays/pull/179) sent. Thanks again!

**Comment by commenthol** [comment]
Thanks for your contribution. v1.8.3 will be released soon...

**Comment by alexfernandez** [comment]
Awesome, thanks! We are looking forward to using your package in our projects :smile: :+1: :clap: :partying_face:
