### ISSUE TITLE
French oversea states incorrectly classified as country

### ISSUE THREAD

**Issue by PerperxityCoding** [commenthol/date-holidays#183]
Hi, thanks for this great tools. This is astonishing work !

The French oversea states are incorrectly classified as countries.
To give a little context, I use it in an app that i'm working on. I have a form, an user can select a country + state (optional) + region (optional) to display the matching holidays.
So the oversea French state should not appear in the country list. I could remove them by hand, still I think this is an issue.

Thanks again for your work
Merci encore pour ce projet tout simplement génial 👍

**Comment by commenthol** [comment]
This project tries to follow IANA (ISO 3166-1 alpha-2) country codes and unicode subdivisions

As stated in the specification under "structure of holidays.yaml" 

> For country codes check:
> https://en.m.wikipedia.org/wiki/List_of_Internet_top-level_domains#Country_code_top-level_domains
> 
> For country codes / divisions / subdivisions - ISO 3166-2:
> http://www.unicode.org/cldr/charts/30/supplemental/territory_subdivisions.html

or a more recent version on subdivisions see https://github.com/unicode-org/cldr/tree/master/common/subdivisions

As I don't like to get involved into discussions where geographical areas (in our context named countries, states, regions) belong to, I have chosen to stick with the standard(s) as much as possible. 

Please consider adapting your application, if you think that some country should be considered differently. 

Wishing you a Happy New Year.

**Comment by PerperxityCoding** [comment]
Thanks for the clarification, it makes sense why it was done this way.

Have an Happy new year.

Thanks again for this projet !
