### ISSUE TITLE
could not parse rule: 1st Friday in December

### ISSUE THREAD

**Issue by Cants820** [commenthol/date-holidays#189]
Hello,

I am currently adding a public holiday on the 1st friday in december and I am getting this error. in my google console 
`could not parse rule: 1st Friday in December`  Here is the entry on my .yaml file: (Note that Farmers' Day is not in the names.yaml) 

Also Farmers' Day exists in my holiday.json

1st Friday in December:
        name:
          en: Farmers' Day
          type: public

**Comment by commenthol** [comment]
Hi @Cants820, Can you please try with "friday" in lowercase? Sorry for the inconvenience but currently all weekdays need to be written in lowercase. I should try to update the parser to cope with correct case for weekday names.
