### ISSUE TITLE
Add Carnival Tuesday as public holiday in Brazil

### ISSUE THREAD

**Issue by adrianoolivr** [commenthol/date-holidays#198]
![Screenshot_20210205_100932](https://user-images.githubusercontent.com/60880274/107038081-c4d74980-679a-11eb-83be-76140d7d3508.png)
This holiday is exactly 47 days before Easter
And ehe tuesday carnival is a public holiday in Brazil
So, please, add 
Font: https://www.inf.ufrgs.br/~cabral/Pascoa.html

**Comment by commenthol** [comment]
@adrianoolivr Can you please give us a reference to a governmental site which states that Shrove Tuesday is a public holiday in Brazil?
On https://pt.wikipedia.org/wiki/Feriados_no_Brasil I could not find a reference stating that in fact it is a public holiday.
