### ISSUE TITLE
Monthly repetition rule

### ISSUE THREAD

**Issue by fsodano1** [commenthol/date-holidays#199]
How can i define these rules:
- every 14th day of every month ?
- every 1st monday of every month ?

Thanks in advance!

**Comment by commenthol** [comment]
```yaml
01-14:
02-14:
...
12-14:

1st monday in January:  
1st monday in February:  
...
1st monday in December:
```

**Comment by fsodano1** [comment]
this possibility was clear to me, but it adds management complexity. Why not create unique and specific rules for these two scenarios?
For example:
1. DD
2 <count> <weekday> (montly)

**Comment by commenthol** [comment]
To my knowledge there is no such holiday rule used in any country so far. 
It may add "management" complexity at your side, but in this lib it would add unnecessary but to-be-maintained code.
