### ISSUE TITLE
AU - NSW holidays

### ISSUE THREAD

**Issue by vwong** [commenthol/date-holidays#2]
According to http://www.industrialrelations.nsw.gov.au/oirwww/NSW_public_holidays/NSW_Public_Holidays.page (which is already in your code comments), there is no public holiday on 31st December for AU/NSW, yet the code has got it specified.  Why is this so?

Also, `npm test` doesn't pass when I tried running it (even without modifications), I get lots of errors, mostly off by half an hour, so I wasn't confident enough to submit a pull request.

I'm using Arch Linux with the latest tzdata-2016j installed, if that indicates anything...

**Comment by commenthol** [comment]
Hi vwong, Thanks for your remark. I fixed New Year's Eve to type=observance and added the Bank Holiday on 1st Monday in August. Can you please review if that's correct.
Regarding tests, there has been updates to moment-timezone for Turkey and Venezuela as they somehow decided to change there time offset. I fixed these tests as well. Currently published is v0.1.6 which includes these fixes.

**Comment by vwong** [comment]
Thanks! I was interested only in public holidays, but Bank Holidays are good too.  All looks good to me.

Re timezones: I assume it uses system timezone data?

**Comment by commenthol** [comment]
No system-timezone-data is used. The module moment-timezone provides them.
```
var hd = new Holidays('au', 'nsw', {types: ['public']})
```
should give you the public holidays only.

**Comment by vwong** [comment]
Sweet! Thanks
