### ISSUE TITLE
Request for Hanukkah 

### ISSUE THREAD

**Issue by Celadora** [commenthol/date-holidays#20]
We request that Hanukkah be added, if that is possible, given that the dates change each year. Thank you!

**Comment by commenthol** [comment]
Yes this can be done. Can you please give me some details to which country, state, region this should be added?

**Comment by Celadora** [comment]
Los Angeles California, US would be ideal for my current uses. Thank you!

**Comment by piotr-s-brainhub** [comment]
IMO the most appropriate would be Israel.

**Comment by commenthol** [comment]
Please check the Israel holidays for Hanukkah.
