### ISSUE TITLE
Please add the Easter Monday to the Quebec (Canada) public holidays

### ISSUE THREAD

**Issue by maxvet** [commenthol/date-holidays#200]
In Quebec, we have the Easter Monday which is the Monday right after the Easter Sunday.

**Here's an official source:**
[https://educaloi.qc.ca/en/capsules/public-holidays/](https://educaloi.qc.ca/en/capsules/public-holidays/)
![Screen Shot 2021-02-13 at 8 55 59 AM](https://user-images.githubusercontent.com/35200170/107851618-5a955900-6dd9-11eb-9de5-805af908b9bd.png)

**Here's also a list of the official holidays of our provincial government:**
[https://www.revenuquebec.ca/en/contact-us/holidays/](https://www.revenuquebec.ca/en/contact-us/holidays/)
![Screen Shot 2021-02-13 at 8 57 34 AM](https://user-images.githubusercontent.com/35200170/107851662-9e885e00-6dd9-11eb-9de9-7fa913ba2714.png)

**Comment by commenthol** [comment]
@sprileyMSTS @brandonbay Can you please help here?

**Comment by commenthol** [comment]
Thanks for rising this issue. v3.0.1 contains the fix.
