### ISSUE TITLE
Disable a holiday

### ISSUE THREAD

**Issue by fsodano1** [commenthol/date-holidays#202]
Is it possibile to use setHoliday method to disable some holiday?
For example, i want to disable a recurring annual Holiday only in a specific year. How can i do It 
programmatically?

**Comment by commenthol** [comment]
Hi @fsodano1, 
I created a [PR](https://github.com/commenthol/date-holidays-parser/pull/31) which will allow you to do that. 

If merged you'll be able to use it in the following way.
E.g. to disable "Thanksgiving" in 2020:

```js
import Holiday from 'date-holiday'

const hd = new Holiday({ country: 'US' })
const rule = hd.getRule('4th thursday in November')
rule.disableIn(2020)
hd.setRule(rule)
```
