### ISSUE TITLE
Is it possible to know if a holiday is a repeating one?

### ISSUE THREAD

**Issue by emgoto** [commenthol/date-holidays#205]
Does the library surface in any way if a public holiday repeats each year on the same date? e.g. 25th December.

**Comment by commenthol** [comment]
This is an interesting request. Just being curious, what is the use-case behind?

Well this project aims to calculate all holidays from rules, so the usual nature of such rule is a repeating one.

I think you'd need to inspect the rules here and check if there is a matching year contained. 
In case you'd find something like "2021-" this would be a non repeating rule.

Of course there are also non-gregorian calendars supported, where you'd need to check them according to the specified rule.

**Comment by emgoto** [comment]
I have a calendar UI where people can input their own holidays - either as
a one-off or as a "repeating" holiday. And I was looking into this library
as a way let users import holidays instead of having it as a manual process.

Yeah, I did see that I could try using the rules, however I assumed there
would be too many edge cases to try and account for.

**Comment by commenthol** [comment]
Maybe you'd like to consider https://commenthol.github.io/date-holidays/ where you can download .ics files for later import in calendars...
