### ISSUE TITLE
Possible to remove the civic holiday from statutory holidays in the province of Quebec (Canada)

### ISSUE THREAD

**Issue by Jassou** [commenthol/date-holidays#207]
The reason, in Quebec, we do not celebrate this day like the other provinces.

Here is a source: 
https://www.officeholidays.com/holidays/canada/canada-civic-day
![Capture d’écran, le 2021-03-09 à 14 37 03](https://user-images.githubusercontent.com/9012744/110528103-bfe11f00-80e5-11eb-8df8-89a495dd533e.png)

**Comment by gerryster** [comment]
Yes, the ability to disable a holiday in a specific locale is a supported feature. See https://github.com/commenthol/date-holidays/blob/master/docs/specification.md#disabling-a-rule-in-states-regions for more information. @Jassou : would you be interested in submitting a pull request with this change? If so, https://github.com/commenthol/date-holidays/blob/master/CONTRIBUTING.md is a good starting point.

**Comment by Jassou** [comment]
@gerryster Thank you for the quick response!

**Comment by commenthol** [comment]
Thanks for rising this issue. v3.0.1 contains the fix.
