### ISSUE TITLE
jest not happy with 3.0.1

### ISSUE THREAD

**Issue by jp928** [commenthol/date-holidays#209]
I got error
```
Cannot find module 'astronomia/julian' from '../node_modules/date-holidays-parser/lib/Julian.cjs'
```

**Comment by commenthol** [comment]
Hi, I just made a cjs project with a small test.

Interestingly the test works without complaints in mocha.
jest on the other hand fails with the stated: 

    FAIL  test/index.test.js
     ● Test suite failed to run

       Cannot find module 'astronomia/julian' from 'node_modules/date-holidays-parser/lib/Julian.cjs'

       Require stack:
         node_modules/date-holidays-parser/lib/Julian.cjs
         ...
         node_modules/date-holidays/lib/index.cjs
         index.js
         test/index.test.js

         at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
         at Object.<anonymous> (node_modules/date-holidays-parser/lib/Julian.cjs:3:14)
     
Due to the observed I would image that jest is not (yet) capable to resolve the package.json exports as used by astronomia. 

Those work according to See https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_resolution_algorithm under PACKAGE_IMPORTS_EXPORTS_RESOLVE.

I think the related issue is https://github.com/facebook/jest/issues/11167

For the moment I would suggest to maintain v2 and v3 of this project. 
The last changes on date-holidays@3.0.1 for CA-QC will be cheery-picked on the v2 branch.

**Comment by hosuaby** [comment]
I had a simular problem while impot `date-holidays` into Angular project:

```typescript
import * as Holidays from 'date-holidays';
```

```
Error: ./node_modules/date-chinese/lib/Chinese.cjs
Module not found: Error: Can't resolve 'astronomia/base' in '/home/hosuaby/projects/my-timesheet/node_modules/date-chinese/lib'
resolve 'astronomia/base' in '/home/hosuaby/projects/my-timesheet/node_modules/date-chinese/lib'
```

There is way to completely exclude `date-chinese` or `astronomia` from bundle ?

**Comment by michaelhays** [comment]
Disregard my last comment! I upgraded `date-holidays` to 3.3.0 and everything is working :)

**Comment by jp928** [comment]
@michaelhays Closed.

**Comment by hosuaby** [comment]
I confirm that `3.3.0` works. With one small problem. For some strange reason code fails in Karma tests with :

```
TypeError: date_holidays_1.default is not a constructor
    at new HolidaysService (http://localhost:9876/_karma_webpack_/webpack:/src/app/locals/services/holidays.service.ts:12:22)
```

But changing import by fixes the problem:

```typescript
import Holidays from 'date-holidays/src';
```

Infortunatly, `3.3.0` still based on plain old CommonsJs modules, so no tree-shakable.

**Comment by commenthol** [comment]
Hi @hosuaby, may I ask why you think that v3.3.0 still relies on CommonJs?

**Comment by hosuaby** [comment]
If I import as following, it import is resolved to file `node_modules/date-holidays/lib/index.cjs`, which is clearly a CommonJs module:

```typescript
import Holidays from 'date-holidays';
```

If I change the imports like that, the import will be resolved by source `node_modules/date-holidays/src/index.js`, which is ES6 module, but it depends on 'date-holidays-parser', which is a CommonJs module:

```typescript
import Holidays from 'date-holidays/src';
```

**Comment by alexsegura** [comment]
On my side, I had the following error: 

```
● Test suite failed to run

  Jest encountered an unexpected token

  This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

  By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

  Here's what you can do:
   • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
   • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
   • If you need a custom transformation specify a "transform" option in your config.
   • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

  You'll find more details and examples of these config options in the docs:
  https://jestjs.io/docs/en/configuration.html

  Details:

  /srv/coopcycle/node_modules/astronomia/data/vsop87Bearth.js:2611
  export default m;
  ^^^^^^

  SyntaxError: Unexpected token 'export'

    at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
    at Object.<anonymous> (node_modules/date-holidays-parser/lib/Equinox.cjs:4:17)
```

If fixed it by adding this to `jest.config.js`

```javascript
{
  transformIgnorePatterns: [
    "node_modules/(?!(astronomia)/)"
  ]
}
```

**Comment by estyxx** [comment]
Hey I still have this problem, tried with the solution suggested above seems working:
I'm using the latest version `"date-holidays": "^3.8.0",` 

```
    Jest encountered an unexpected token
.....
    Details:

    /Users/ester.beltrami/Made/mercury/node_modules/astronomia/data/vsop87Bearth.js:2611
    export default m;
    ^^^^^^
```
If I change to import `import Holidays from 'date-holidays/src';` instead I got this:

```
    /Users/ester.beltrami/Made/mercury/node_modules/date-holidays/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export { Holidays as default } from './Holidays.js'
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import Holidays from 'date-holidays/src';
        | ^
      2 |
      3 | const hd = new Holidays("GB", "ENG");
      4 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1479:14)
      at Object.<anonymous> (src/lib/hooks/useNextBusinessDay/index.tsx:1:1)


```

**Comment by axe-me** [comment]
Add a module mapper into jest.config.js solved my problem:
```js
moduleNameMapper: {
    "astronomia/data(.*)$": "<rootDir>/node_modules/astronomia/lib/data$1.cjs",
  },
```
