### ISSUE TITLE
No Good Friday dates are returned for US

### ISSUE THREAD

**Issue by trisrael** [commenthol/date-holidays#219]
Although referenced in several files there is no 'Good Friday' in the [US YAML](https://github.com/commenthol/date-holidays/blob/master/data/countries/US.yaml) but it is referenced [all over the place](https://github.com/commenthol/date-holidays/search?p=6&q=Good+Friday) including past test fixtures for what looks like US, so this is likely a regression?

When calling:
```
const hd = new Holidays('US');
const holidays = hd.getHolidays(); // holidays does not include any named: 'Good Friday'
```

**Comment by commenthol** [comment]
According to the data there is no official holiday across the US. It is celebrated only in some states.  
If you name the proper state on initialization e.g. `new Holidays('US', 'CI')` (for Connecticut) you should see the Good Friday as a holiday.
If you think Good Friday is observed in the whole country albeit not being a public holiday in all of the states, please consider changing your issue.

**Comment by commenthol** [comment]
Please reopen for further comments...
