### ISSUE TITLE
Can you please add good documentation how use it with React/Angular/Vue, because I spent already two days and still can not use it.

### ISSUE THREAD

**Issue by maxizhukov** [commenthol/date-holidays#220]
Requires are not working, and all that described in Line "Browser", is not clear, there are some fixed files but how to use them?

**Comment by commenthol** [comment]
v3 of this library uses es6 modules. v2 uses cjs. 
Please take a note here that you use v3 for imports.
Please also consider that this wont work with jest #209.
This is a library which you could use the "classic" way with UMD or any bundler will work. 
Take a look at examples/browser/*. To see it live and in colors check https://commenthol.github.io/date-holidays/.
As being independent from and frontend framework there is point to me why this should not work with react/vue/...

**Comment by commenthol** [comment]
Have fun with https://github.com/commenthol/date-holidays-react-example

**Comment by marinabrcls** [comment]
Thank you!!! This really helped! 👍🏼
