### ISSUE TITLE
How can I add import the HK canlender to your work?

### ISSUE THREAD

**Issue by kvtong93** [commenthol/date-holidays#221]
Hi commenthol,

I am a user from Hongkong, however, i didn't see the HK holiday list in your work, so how can i make this list?

**Comment by commenthol** [comment]
Hi @kvtong93,
there is a todo file at https://github.com/commenthol/date-holidays/blob/master/data/countries/HK.todo. 
You may use this as a template.  Rename to HK.yaml and get started.
Please also check the specification as the contributing guidelines.
Your PR is very welcome.

**Comment by kvtong93** [comment]
Hi commenthol,

thanks for your reply, may I have an exmaple of China mainland? So I can  well understand how to fill with.

发自我的iPhone

**Comment by commenthol** [comment]
Please take a look in data/countries. There you'll find what you are looking for.
Please also consider reading CONTRIBUTING.md as well as docs/specification.md first.

**Comment by kvtong93** [comment]
Hi commenthol,

I have a question about some holiday is based on lunar calendar how can i do with this. and how to set saturday and sunday as weekdays?

发自我的iPhone

**Comment by kvtong93** [comment]
HI Commenthol,

Please refer to below:

https://en.wikipedia.org/wiki/Lunar_calendar

It’s Chinese traditional calendar.

**Comment by commenthol** [comment]
https://github.com/commenthol/date-holidays/blob/master/docs/specification.md#dates-in-chinese-calendar-lunar
Please be so kind and read the spec.

**Comment by commenthol** [comment]
Hi @kvtong93, Can you please review #257 and let me know if the rules are correct.
Thanks in advance for your help.
