### ISSUE TITLE
[Feature Request] holiday function for searching for holidays using keywords

### ISSUE THREAD

**Issue by kodie** [commenthol/date-holidays#24]
Hi there! I am the maker of https://github.com/kodie/moment-holiday and I'm considering switching my holiday source to your package here. Unfortunately, this package is missing one feature that I need, to be able to search for holidays using keywords.

I could implement this in my package and have something like keywords.json in it, but I think it would be better for everyone if the keywords were contained in the same package as the data source.

So my suggestion is to implement a holiday function for searching for holidays using keywords.

For example:
```javascript
var hd = new Holidays('US')
hd.holiday('Memorial Day')
```

This would involve adding the `keywords` and `keywords_n` to the `holidays.yaml` structure.

Both of these keys would accept an array of strings and/or regex strings. `keywords` would be used as expected and `keywords_n` would be for values that shouldn't apply to that holiday. For example, the holiday Christmas Day would have `['christ', 'x-?mas']` in it's `keywords` and `['eve']` in it's `keywords_n`.

I would be more than happy to work on this and submit a pull request.

**Comment by commenthol** [comment]
Hi @kodie, thanks for your feature request. To be honest I do not fully understand the need for maintaining your requested keyword list. I understand to filter/search for holidays is a nice to have and should be possible to implement as some sort of postfilter across the available langs. As I still plan to support holidays across the world, I fear the additional effort of supporting those keywords and its necessary test cases. 
Maybe you are able to extract your keywords from patterns provided by the already existing date labels?

**Comment by kodie** [comment]
@commenthol I understand not wanting to maintain keywords. I would also probably suggest minimal testing for keywords (ie, just test a couple of keywords to make sure the function is working correctly). I suppose I could create an add-on package, something like `date-holidays-search` if you don't wish to implement this functionality into your package.

**Comment by kodie** [comment]
@commenthol Nevermind this. I have decided to work on a package that extends your package and adds additional functionality. However, one thing that is stopping me is [this issue](https://github.com/commenthol/astronomia/issues/2) with your [astronomia](https://github.com/commenthol/astronomia) package.
