### ISSUE TITLE
"Hijra Dates" are unusable - Dates slide from 6 hours

### ISSUE THREAD

**Issue by DaedalusDev** [commenthol/date-holidays#258]
Hello,

some weeks ago, we have submit some pull requests to your repo in order to complete your library with some islamic countries.

Unfortunately, we are facing some serious errors while using the library.

### Step to reproduce
1. Generate an holiday instance
2. Define "MA" (Morocco) as state
3. Check if `2021-06-26T18:00:00` is holiday 2000 times in a row (work for every dates)
   - `false` 93 times
   - `true` 4 times
   - `false` 76 times
   - `true` 4 times
   - `false` 276 times
   - `true` 4 times

### Reproduction code
```js
const holidayInstance = new Holidays('MA')
holidayInstance.setLanguages(['en'])
for (let i = 0; i < 2000; ++i) {
  const isHoliday = holidayInstance.isHoliday(new Date('2021-06-26T18:00:00'))
  if (isHoliday) {
    console.log('WTF ?')
    console.log(isHoliday.map(({ name, date }) => `${name} (${date})`))
  } else {
    console.log('Nope.jpg')
  }
}
```

### Screenshot result
![image](https://user-images.githubusercontent.com/16138648/122026355-68c8a580-cdca-11eb-81d9-95aded466a1d.png)

## Platform
**Version** : 3.5.1
**OS** : Ubuntu 20.04
**Browser** : Chrome 91.0.4472.77

## Other
I think we found a mutation / side effect in your code. It looks like the holidays slide from 6 hours each time the method is called.

Thanks for your great works ! You made a powerfull, testable, reliable and scallable library with your data driven system ! We did not found such a clean work in other holidays libraries in other languages !

**Comment by DaedalusDev** [comment]
We investigate and found an issue in "cache" mechanism in a sibling library [date-holiday-parser](https://github.com/commenthol/date-holidays-parser).

In [src/Holidays.js#L388](https://github.com/commenthol/date-holidays-parser/blob/a9b244f1e4a5d6ce89704351f4d172bd17904ed8/src/Holidays.js#L388), the method `_rule.fn.inYear(year)` is called. 
```js
  _dateByRule (year, rule) {
    const _rule = this.holidays[rule]
    const dates = _rule.fn.inYear(year) // <= Here
      .get(this.__timezone)
    // ...
```

At first call, the cache is generated but will produce a side effect for each other calls in [src/DateFn.js#L28](https://github.com/commenthol/date-holidays-parser/blob/a9b244f1e4a5d6ce89704351f4d172bd17904ed8/src/DateFn.js#L28). Comment the following code disable the cache system but fix the issue.
```js
  inYear (year) {
    // if (this.cache.has(year)) {
    //   this.event = this.cache.get(year)
    //   return this
    // }

    let ruleFn // current rule
   //...
```

### Why the date is offset from 6 hours each calls ?
In [src/Holidays.js#L389](https://github.com/commenthol/date-holidays-parser/blob/a9b244f1e4a5d6ce89704351f4d172bd17904ed8/src/Holidays.js#L388), the method `.get(this.__timezone)` is called. 
```js
  _dateByRule (year, rule) {
    const _rule = this.holidays[rule]
    const dates = _rule.fn.inYear(year)
      .get(this.__timezone) // <= Here
    // ...
```

For `Hijri` dates, the following method will call [Hijri.js#L17](https://github.com/commenthol/date-holidays-parser/blob/a9b244f1e4a5d6ce89704351f4d172bd17904ed8/src/Hijri.js#L17)
```js
   get (timezone) {
    const arr = this.dates.map((date) => {
      const o = {
        date: date.toString() + ' -0600',
        start: date.setOffset(-6, 'h').toTimezone(timezone),
        end: date.toEndDate().toTimezone(timezone)
      }
      this._addSubstitute(date, o)  // <= This method mutate cached value and will result an offset of 6 hours each time the method is called
      return o
    })
    return arr
  }
```

**Comment by commenthol** [comment]
Hi @DaedalusDev, 
Thank you very much for your bug description and your proposed changes.
Indeed those resolved the issue described. 
On https://github.com/commenthol/date-holidays-parser/pull/33 you'll find the relevant fix.

**Comment by commenthol** [comment]
date-holidays-parser@3.2.1 should have the fix included. 
Thanks again and have fun with it.
