### ISSUE TITLE
UMD version not working since switch to esm module

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [commenthol/date-holidays#260]
Ever since the switch to an esm module in v3.0.0, `dist/umd.min.js` no longer works. I'm not sure exactly what's wrong with it, but the global `Holidays` object no longer gets defined in modern browsers like Chrome or Firefox, and IE11 (which we unfortunately still need to support) gives error `SCRIPT438: Object doesn't support property or method 'trunc'` (obviously, no `Holidays` object is created either).

Here's a very simple HTML page to demonstrate the problem:
```html
<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset="UTF-8">
<script src="node_modules/date-holidays/dist/umd.min.js"></script>
</head>
<body>
<div id="outputArea"></div>
<script>
var hd = new Holidays();
document.getElementById("outputArea").innerHTML = JSON.stringify(hd.getCountries());
</script>
</body>
</html>
```
If opened from a node.js project with `date-holidays@2.1.1` installed, it prints the supported countries. If opened from a project with `date-holidays@3.6.0` installed, nothing is displayed.

**Comment by commenthol** [comment]
Please use:
```html
<script>
var hd = new Holidays.default();
document.getElementById("outputArea").innerHTML = JSON.stringify(hd.getCountries());
</script>
```

**Comment by ehoogeveen-medweb** [comment]
Thanks, I'll update our code to use that (the 'trunc' error in IE11 was due to missing core-js in the testcase, should have figured that out myself).
