### ISSUE TITLE
Custom holidays.json build - how to use?

### ISSUE THREAD

**Issue by centi** [commenthol/date-holidays#268]
Hi, I need to use a custom build of holidays.json (to reduce its size), but the documentation only describes how to create this build, but it doesn't show how to use it.

In our project, we use date-holidays as a NPM dependency. Is there a way to "inject" the custom JSON? I've read the API documentation as well, but I see no way, how to pass the JSON.

Can you please add information about how to use the custom JSON or direct me to a existing documentation with this information?

**Comment by commenthol** [comment]
Please consider documentation and take a look at [date-holidays-parser](https://github.com/commenthol/date-holidays-parser) if you want to use your custom lists. 
Please consider contributing changes which fix, update or add new holidays for the benefit of all using this lib.
