### ISSUE TITLE
Why there is no Chung Yeung Festival?

### ISSUE THREAD

**Issue by rantianhua** [commenthol/date-holidays#273]
Is there any reason that no Chung Yeung Festival in CN?

**Comment by commenthol** [comment]
For Chinese public holidays the information was taken from Wikipedia as attributed.
Doing some research I found this official site http://www.gov.cn/zhengce/content/2020-11/25/content_5564127.htm for 2021.
Obtaining more information is difficult for me.
Could you please compile a list of public and observed holidays in China?
A PR would also be appreciated.
