### ISSUE TITLE
No longer working directly in browsers

### ISSUE THREAD

**Issue by jk-12345** [commenthol/date-holidays#280]
Hi,

Firtly, this library is great and thanks for the nice work.

I have some issues : the only versions that directly work (CDN source) in a browser are the ones previous to version 3.0.0. And the 3.0.0 and above are not working (I get new Holiday is not a cosntructor error).

Why so ?

Thanks for helping out

**Comment by ehoogeveen-medweb** [comment]
I encountered the same problem in #260: The solution is to replace `new Holidays()` with `new Holidays.default()` in your code.
