### ISSUE TITLE
How can I use this package in react native applications? (However, this package itself specifies a main module field that could not be resolved )

### ISSUE THREAD

**Issue by rubanraj54** [commenthol/date-holidays#292]
Hi,

Thanks for the great package.

I would like to use this package in react native applications, but I am getting the following error.

<img width="396" alt="Screenshot 2021-11-22 at 17 15 04" src="https://user-images.githubusercontent.com/10024405/142896425-dd56f601-f3a8-41a5-9630-697784cba206.png">

I tried this solution(https://stackoverflow.com/a/60126739/2708249) but didn't work.

Could you/anyone please let me know how can I use this package in react-native applications?

Thanks.

**Comment by RosCoder** [comment]
@rubanraj54
Hey! Metro does not support packages with `.cjs` sources. This solution works for me:
https://github.com/facebook/metro/issues/535#issuecomment-970443661

**Comment by rubanraj54** [comment]
@RosCoder Thanks for the hint, let me try your solution.

**Comment by rubanraj54** [comment]
@RosCoder Thanks, your solution fixed the issue.

**Comment by sid028** [comment]
Getting same issue : https://stackoverflow.com/questions/74318272/date-holidays-invariant-violation-module-appregistry-is-not-a-registered-calla
