### ISSUE TITLE
Reduce bundle size to only 1 country in Angular

### ISSUE THREAD

**Issue by Gillardo** [commenthol/date-holidays#310]
How can i do this, i only need 1 country at the moment, and the js files have increased in size loads.

We are using Angular 13.

Also we are getting this message.
![image](https://user-images.githubusercontent.com/7406381/149968317-30166abc-b858-429e-96a3-d79430166a22.png)

Is this project going to be updated as moment-timezone is now considered an out-dated project

**Comment by commenthol** [comment]
1. RTFM
2. luxor or date-fn still have problems with dates switching from or to DST. During that "switching" times the date conversions are wrong. Therefore I still have to stick with moment-timezone as being the only source where the conversions are correct.
