### ISSUE TITLE
Suggestion: add id to recognize the holiday in the years

### ISSUE THREAD

**Issue by CodingByJerez** [commenthol/date-holidays#311]
it's all in the title :) I think it would be interesting to add a unique ID to recognize the holiday in years. 
 It would make it possible to make recurrences cleaner than compared to the name.

if not is it possible to use the "rule" as ID?

**Comment by commenthol** [comment]
Reading old issues might provide reasonable answers #10 #153

**Comment by KyleMo** [comment]
https://www.npmjs.com/package/date-holidays-with-ids
