### ISSUE TITLE
Can you support for Iran

### ISSUE THREAD

**Issue by ALi-Hosseinzad** [commenthol/date-holidays#319]
Please provide support for Iran. Refer to the below link:
[https://www.timeanddate.com/calendar/?year=2022&country=75]()

**Comment by commenthol** [comment]
Hi @ALi-Hosseinzad,
I am confused as you state in the headline "Iran" but request support for "India".
Supposing you are asking for support for Iran I would be happy if you could help us here.
The current library supports the islamic calendar using Hijra Dates calculated according to https://www.ummulqura.org.sa/
If these calculations also apply for Iran, please consider looking at our [specification](https://github.com/commenthol/date-holidays/blob/master/docs/specification.md) and some supported countries where these festivities are also celebrated.

**Comment by ALi-Hosseinzad** [comment]
Hi @commenthol 
I am sorry about "India" that was a typing error.
No Iranian calendar is very different from the Islamic calendar. 
you can see in this link:
[](https://www.iranian-calendar.com)
The Iranian calendar completely is different from other calendars.

**Comment by commenthol** [comment]
Hi @ALi-Hosseinzad, 
I've created PR #335 which adds support for Iran. Can you please check the holiday names its translations and dates? 
https://github.com/commenthol/date-holidays/pull/335/files#diff-56525628d7df491ff8870eb224bef31ec95e988dee4fd71be7e8c9f3beed7064

**Comment by ALi-Hosseinzad** [comment]
Hi @commenthol 
Thank you for your attention,
Yes, It completely is true,

**Comment by commenthol** [comment]
v3.15.0 now contains Iranian holidays.
