### ISSUE TITLE
DE-HE 12-31 is not really a public holiday

### ISSUE THREAD

**Issue by HBM08** [commenthol/date-holidays#321]
It seems that for 12-31 only retailers have to close after 14:00 but the rest of the guys need to work, so I guess this would make it also a bank holiday and not a public one right?

**Comment by commenthol** [comment]
You are right for the states HB, HE, TH. In these states each Sunday is counted as a public holiday.
Maybe it is best to remove all the rules containing "12-31 14:00 if sunday then 00:00".
The country wide rule at https://github.com/commenthol/date-holidays/blob/ac5b863aa1f8e9bb5de54ade2d101da4df44c95b/data/countries/DE.yaml#L108-L110 would already be correctly attributed as you propose.

**Comment by HBM08** [comment]
> You are right for the states HB, HE, TH. In these states each Sunday is counted as a public holiday. Maybe it is best to remove all the rules containing "12-31 14:00 if sunday then 00:00". The country wide rule at
> 
> https://github.com/commenthol/date-holidays/blob/ac5b863aa1f8e9bb5de54ade2d101da4df44c95b/data/countries/DE.yaml#L108-L110
> 
> would already be correctly attributed as you propose.

That is really great, thanks for fixing it that fast :) 
Any idea when would this be deployed and available ?
