### ISSUE TITLE
Good Friday is not a public holiday in AT

### ISSUE THREAD

**Issue by digitalw** [commenthol/date-holidays#323]
I get Good Friday (e.g. 15.04.2022) as a public holiday in AT. This has changed in 2019 (https://www.arbeiterkammer.at/beratung/arbeitundrecht/Arbeitszeit/ArbeitszeitundRuhepausen/Persoenlicher_Feiertag.html)

**Comment by commenthol** [comment]
Hi @digitalw, 
Good Friday is attributed as "optional". See https://commenthol.github.io/date-holidays/#-/2022/AT

**Comment by commenthol** [comment]
@digitalw is optional the correct attribution here?

**Comment by digitalw** [comment]
Hi, Thanks.
I'm not sure about the optional. As far as I can tel, it used to be an optional holiday (Protestant), and is now no holiday at all.
