### ISSUE TITLE
Get holiday time on respective location's time

### ISSUE THREAD

**Issue by dlcaio** [commenthol/date-holidays#324]
Hey guys, really nice work, congratulations!

I was wondering if there's a way to retrieve holidays in their respective local time, without timezone.

In a way that, as an example, Christmas day's start date and end date would be the same for all locations that celebrate it. Start date would be something like "2022-12-25 00:00:00" for this year.

Is that by any chance possible already ? Would be pretty helpful.

Cheers! : D

**Comment by commenthol** [comment]
Each date object returns `date`, `start`, `end`, `name` and `type`

Only `start` and `end` respect the timezone of the country, where `date` represents the "local" date.

e.g.
```js
const ev = {
  date: '2015-01-01 00:00:00',
  start: '2014-12-31T23:00:00.000Z',
  end: '2015-01-01T23:00:00.000Z',
  name: 'Any nou',
  type: 'public',
  rule: '01-01'
}

// gets "local" date
const localStart = new Date(ev.date)
const localEnd = new Date(localStart.getTime() + new Date(ev.end).getTime() - new Date(ev.start).getTime())
console.log(localStart, localEnd)
```

**Comment by dlcaio** [comment]
Hey @commenthol, that makes sense, I didn't realize there was `date` prop that was in local time.

I think I stumbled on another solution, just using `setTimezone()` and passing `timezone` as an undefined argument. From the docs:

```js
/**
 * sets timezone
 * @param timezone - see `moment-timezone`
 * if `timezone` is `undefined` then all dates are considered local dates
*/
setTimezone(timezone: string): void;
```
Thanks for the fast response : D
