### ISSUE TITLE
Possible to move the data to a separate repository?

### ISSUE THREAD

**Issue by Alxandr** [commenthol/date-holidays#326]
Hi. I'm looking into creating a similar project to this in rust, and I think it would be a real shame to have to duplicate the effort of keeping the data-set up to date, so I was wondering what you thought about moving the data-set to a separate repository that can be included either as a git-module, or kept in sync using some github actions? That way, there could be multiple projects collaborating on the same dataset?

**Comment by commenthol** [comment]
Hi @Alexandr,
That's great news that you want to spend the efforts on using this data-set for a rust based parser.
I think the project is already structured the way you are proposing.
This repository contains solely the data and the assigned test-set together with some build scripts.
The parser is already in a different repository.
For running the tests a very thin layer exposing the parser together with some types is offered.
Removing this already thin layer I think complicates things for contributing to the data-set, as there would be no clear connection between this main-project and the "outsourced" data-set then.

**Comment by Alxandr** [comment]
I see. I just saw the `src` folder and assumed the functionality lived in there, but it's just a thin shim to the parser. I would argue that this is a tiny bit confusing - but it's not a big deal. I'll just sub-module in this repository and get working on getting things working for now, and we'll see how far I get :).
