### ISSUE TITLE
Minifing error with create-react-app

### ISSUE THREAD

**Issue by rinaldoleone** [commenthol/date-holidays#33]
Hi,
First of all, thank you for this module! When I try to use it with _create-react-app_, an errror occurs during the npm run build command. It says: 

```
Failed to minify the code from this file: 

 	./node_modules/date-holidays-parser/src/CalEvent.js:3 
```
Any help?

Thank you!

**Comment by commenthol** [comment]
Please use in your webpack config:

```
resolve: {
  mainFields: ["browser", "main", "module"]
}
```

please take a look here:
<https://webpack.js.org/configuration/resolve/#resolve-mainfields>

**Comment by commenthol** [comment]
Closing...

**Comment by kneza23** [comment]
Webpack config is hidden from developer when you use create-react-app. It's meant to work out of the box. So the problem is not solved. :). Anyone solved this problem without editing webpack config?
