### ISSUE TITLE
26-Dec-2022 is a replacement substitute holiday for Malaysia

### ISSUE THREAD

**Issue by albertchua** [commenthol/date-holidays#332]
26-Dec-2022 is a replacement substitute holiday for Malaysia. It's missing from the 2022 calendar.
![image](https://user-images.githubusercontent.com/50098198/164588089-5f97e37e-115f-4284-8822-d0e641d7400c.png)

**Comment by commenthol** [comment]
PR #330 should have solved your issue. See https://commenthol.github.io/date-holidays/#-/2022/MY
