### ISSUE TITLE
Error date-holidays-parser/src/CalEvent in ? - Expected identifier

### ISSUE THREAD

**Issue by tdrake-cb** [commenthol/date-holidays#34]
I am getting the following error when in Internet Explorer 11.

Error date-holidays-parser/src/CalEvent in ? - Expected identifier

This is for the following line.

```const {isDate} = require('./internal/utils')```

My guess is it is interpreting the destructuring assignment as an object. My project is based off of react-boilerplate and is using babel-polyfill instead or core-js, not sure if that is the cause. Any ideas what could be causing this?

**Comment by commenthol** [comment]
Hi,

This seams to be related to the webpack config as IE11 requires ES3.


Please use in your webpack config:

```
resolve: {
  mainFields: ["browser", "main", "module"]
}
```

please take a look here:
https://webpack.js.org/configuration/resolve/#resolve-mainfields

**Comment by commenthol** [comment]
Closing...
(no feedback is considered as good news)
