### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by muzamalidrees** [commenthol/date-holidays#340]
Hi guys,
I am using this library in my react app, I want to update the version from 1.8.3 to 3.16.0. but when I updated the version I am having this error on npm start:

![image](https://user-images.githubusercontent.com/47274591/172623386-202c1ff7-bd05-426c-b58c-18cfc51985af.png)

Can you guys get me the way to solve this?
Thank you!

**Comment by commenthol** [comment]
Can you take a look at #315?
I think this is related to your projects setup.

**Comment by muzamalidrees** [comment]
> Can you take a look at #315? I think this is related to your projects setup.

**Comment by muzamalidrees** [comment]
@commenthol  #315  suggests a solution for jest config and I m not using jest at all.
