### ISSUE TITLE
23rd of June is not a holiday in Norway

### ISSUE THREAD

**Issue by erikskaar** [commenthol/date-holidays#341]
As the title states, June 23 is not a holiday in Norway. It is a 'merkedag', which means that it is a day to be noted, but it is not a holiday in any shape or form.

**Comment by commenthol** [comment]
Hi @erikskaar,

This project distinguishes the "holidays" into different types. See [type-of-holidays](https://github.com/commenthol/date-holidays/blob/master/docs/specification.md#types-of-holidays).

Midsummar Eve is attributed as [type=observance](https://github.com/commenthol/date-holidays/blob/820593b7eac5457469a1ad22636360217863f2b1/data/countries/NO.yaml#L56) which should have a similar meaning as "merkedag" or notable event.

**Comment by erikskaar** [comment]
Oh, my bad. Thanks :)
