### ISSUE TITLE
Holidays in Argentina

### ISSUE THREAD

**Issue by sebastianarena** [commenthol/date-holidays#343]
Hello there!
Here's a list of holidays for Argentina in 2022: https://www.argentina.gob.ar/interior/feriados-nacionales-2022
From what I see, you'll need to add the following to the current list:

October 7th: an added holiday with tourists means
November 20th: should be in place of November 28th
November 21st: an added holiday with tourists means

**Comment by commenthol** [comment]
Hola @sebastianarena,
Gracias por la notificación. ¿Me puedas verificar los cambios dentro el PR #344?

**Comment by sebastianarena** [comment]
@commenthol parece estar todo bien!
