### ISSUE TITLE
Warning when building in angular 14 project

### ISSUE THREAD

**Issue by Gillardo** [commenthol/date-holidays#348]
This was ok when i was using angular 13 which i believe targets es2018, but since updating i am getting these errors.

![image](https://user-images.githubusercontent.com/7406381/185065919-01b21ea4-72bc-47ff-85b1-ee1edd0587a9.png)

Here is my tsconfig

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2020",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ],
  }
}
```

**Comment by commenthol** [comment]
Hi @Gillardo,
As said this project offers both ESM and CJS via package.json exports. 
If you think the issue is unrelated to your project setup, please provide a fix via a PR.

**Comment by Gillardo** [comment]
Sorry but i do not think this is correct.  It also states this on the deepmerge github
https://github.com/TehShrike/deepmerge/issues/250

Which as i stated, was one of the errors when using your library
![image](https://user-images.githubusercontent.com/7406381/187092399-d2f4210f-c72d-4519-bd1d-4cac08acd711.png)
