### ISSUE TITLE
Jeune federal is not an official holiday in Geneva, Switzerland

### ISSUE THREAD

**Issue by leykee** [commenthol/date-holidays#350]
https://github.com/commenthol/date-holidays/blob/7721e58f6f8dfd5762c8741e28aacdf38c2f6565/data/countries/CH.yaml#L678

**Comment by kevinley** [comment]
Instead they have the Jeune Genevois, which is already defined in the CH-GE specific holidays

**Comment by commenthol** [comment]
Thanks
