### ISSUE TITLE
support for Israel

### ISSUE THREAD

**Issue by oprogramador** [commenthol/date-holidays#36]
I would like a support for the public holidays of the State of Israel (as `IL: 'ישראל'`).
The list: https://www.timeanddate.com/holidays/israel/

If you don't have enough time, I can open a PR.

**Comment by commenthol** [comment]
Yes please. PR is welcome.

**Comment by argasek** [comment]
@oprogramador Any progress on this?

**Comment by oprogramador** [comment]
@argasek currently I have no enough time

**Comment by rikur** [comment]
@oprogramador got time now? I'd love to help, but those holidays look tricky..

**Comment by oprogramador** [comment]
@rikur 
I haven't had time for that and I haven't had a real need for supporting Isreal on any app, I just thought it would be great to give such support.

Initially I tried to implement that but it seems to not be so easy.

**Comment by rikur** [comment]
I was able to download the Israeli holidays from hebcal.com and use the alongside date-holidays. Since the holidays are not based off Gregorian calendar, it might be impossible to have them laid out in a future-proof way for this library.

**Comment by gerryster** [comment]
Note that this library does have support for the Hebrew calendar. See https://github.com/commenthol/date-holidays/blob/master/docs/specification.md#dates-in-hebrew-calendar . PR's are welcome. Also, if someone has links to primary source documentation for official Israeli holidays that is also a good place to start. For example, links to official legislation, government, or religious sources for holidays. Links to third party holiday aggregator sites are not as helpful.

**Comment by rikur** [comment]
@gerryster hebcal is a full-blown JS implementation of Hebrew calendar: https://github.com/hebcal/hebcal-js

I would just assume that it's too heavy to implement into this project.

**Comment by commenthol** [comment]
Hi @argasek, @oprogramador, @rikur PR#296 adds support for Israel holidays. 
Would you mind reviewing the proposed?

**Comment by rikur** [comment]
I'm not local to the area, but I checked a few dates and seemed to match with what I have.

**Comment by oprogramador** [comment]
@commenthol 

Thanks for your PR.

I compared only 2022 with https://www.timeanddate.com/holidays/israel/2022 and I found some errors. Some of the holidays in your PR don't seem to be in this list.

**Comment by oprogramador** [comment]
@commenthol 

Thanks for your implementation and merging my PRs.

Now I close it as it's already implemented but please take a look at https://github.com/commenthol/date-holidays/issues/309
