### ISSUE TITLE
Unique identifier for the holiday

### ISSUE THREAD

**Issue by hamboomger** [commenthol/date-holidays#360]
Hello, I need a way to tell if 2 holidays from different countries are the same holiday (for example Internation Women's Day), but still be able to display the name of the holiday in the native language. If you want I can make a PR myself :)

**Comment by commenthol** [comment]
Hi @hamboomger,
There is already a "unique identifier" by the `rule` attribute itself. 
Your described usecase is kind of special, therefore I don't see the need to add this into this project.
The provided data and the parser are IMHO generic enough that you can build your usecase independently.
