### ISSUE TITLE
Easter isn't listed as a holiday for DE-HE 2021

### ISSUE THREAD

**Issue by pmlk** [commenthol/date-holidays#361]
This issue came up after upgrading from `3.8.0` to `3.16.7`. It seems to have started with version ~~`3.15.0`~~ `3.14.5`.

This may be related to #14, since Easter is always on a Sunday, it may not be considered a holiday. However, "2. Weichnachtstag" was also on a Sunday in 2021, but it is listed as a holiday. So if excluding all Sundays were a rule, it seems to be a bit inconsistent.

**Comment by commenthol** [comment]
Hi @pmlk, I have check the data in DE.yaml but there has not been an attribution on easter for Hessen so far. 
If easter shall be added for DE-HE, please consider filing a PR.

**Comment by pmlk** [comment]
I'd be happy to file a PR, but I would need some help as I don't quite understand the syntax in the yaml files.

Also, I do see something for easter for DE-HE: https://github.com/commenthol/date-holidays/blob/master/data/countries/DE.yaml#L200

As said, it did show up before version `3.14.5`, but I don't quite understand why it vanished.

**Comment by commenthol** [comment]
Hi @pmlk ,
I created PR#365 which should fix the issue. I would also consider Pentecost as public holiday then.
Please advise if changes are required.

**Comment by pmlk** [comment]
Awesome! Thank you! [According to Wikipedia](https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland) Pentecost is also a public holiday in Hessen. So that looks good to me 👍 

Thank you so much! 🙏
