### ISSUE TITLE
02.11 is not a holiday in Germany, 01.11 also only in some states.

### ISSUE THREAD

**Issue by reschandreas** [commenthol/date-holidays#366]
Hi! I noticed that the second of november is marked as a holiday in Germany, according to https://de.m.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland that's not true. Also the first of November is a holiday in 5 out of 16 states, not everywhere.

**Comment by commenthol** [comment]
Hi @reschandreas,

Can you please check https://github.com/commenthol/date-holidays/blob/master/docs/specification.md#types-of-holidays?

The holidays all have different types which are in accordance with your stated source.

**Comment by reschandreas** [comment]
Hi @commenthol , sorry, I should've checked the docs. Thank you very much!
