### ISSUE TITLE
School holidays

### ISSUE THREAD

**Issue by J-Hoh** [commenthol/date-holidays#368]
Shouldn't "school" type holidays include the actual school holidays?

Listed below is an example of the past months fall break here in germany across different states:
![image](https://user-images.githubusercontent.com/64546226/200068491-e49c3796-f30e-44fc-a01f-5d033c903871.png)

So far the country *.yaml's only contains single days, mostly bridging actual public holidays.
The only downside I'm seeing is a pollution of the holidays data, as the actual dates can't simply be repeated but are set by the higher ups. For example: [germany's summer vacation](https://www.kmk.org/service/ferien.html)
16 states with each ~6 Vacation ranges, per year -> 96 more lines/year?

In the meantime I'm adding all vacations I need with the API's setHoliday

**Comment by J-Hoh** [comment]
Much like suggested in #367 I'll probably introduce my own calendar.
I am still wondering if anyone else would need such a repository of vacations, y'know when I'm already creating one.

**Comment by commenthol** [comment]
Hi @J-Hoh,
I would not mind if you like to add this information into this project, unless you also like to maintain this information over some years.
As this library is primarily intended for a server side use I don't mind the additional lines.
