### ISSUE TITLE
Failed to minify the code

### ISSUE THREAD

**Issue by kneza23** [commenthol/date-holidays#37]
When using create-react-app there is problem with minifying.
`./node_modules/date-holidays-parser/src/CalEvent.js:3 `

Please read more here: http://bit.ly/2tRViJ9

Ps. we can't edit webpack config file in create-react-app environment.

**Comment by commenthol** [comment]
Could you please try with v1.2.5 and post your findings here?

**Comment by commenthol** [comment]
closing...
