### ISSUE TITLE
Argentina is getting Nov 20th wrong

### ISSUE THREAD

**Issue by sebastianarena** [commenthol/date-holidays#371]
Hello,
Argentina has a holiday on Nov 20th.
For some reason this year they also decided to do Nov 21th.
The main problem is that for some reason is showing Nov 28th as the actual holiday.
Here's a calendar for 2022: https://www.argentina.gob.ar/interior/feriados-nacionales-2022
Thanks

**Comment by commenthol** [comment]
Hi @sebastianarena ,
I cannot reproduce as our test fixture set states that Nov 21th is calculated as the holiday.
Please take a look at https://github.com/commenthol/date-holidays/blob/master/test/fixtures/AR-2022.json#L147
