### ISSUE TITLE
Wrong dates calculated for a few 2023 Singapore holidays

### ISSUE THREAD

**Issue by aradnom** [commenthol/date-holidays#387]
Somebody in Singapore passed this on to me, confirmed it [here](https://www.mom.gov.sg/newsroom/press-releases/2022/0408-public-holidays-for-2023).

- Hari Raya Puasa, calculated as 2023-04-21, actual date is 2023-04-22
- Vesak Day, calculated as 2023-05-05, actual date is 2023-06-03
- Hari Raya Haji, calculated as 2023-06-28, actual date is 2023-06-29

Checked this on the latest version of the package, 3.16.12. Let me know if there's any other info I can provide.

Thanks for all of your work on `date-holidays` by the way, it's been a super useful reference. 👍

**Comment by commenthol** [comment]
Hi @aradnom, Thanks, Patch v3.16.13 is on its way...

**Comment by gedclack** [comment]
Thanks @aradnom and @commenthol for the updates 🚀
