### ISSUE TITLE
provide custom holidays for isHoliday()-Check

### ISSUE THREAD

**Issue by dominikstohl** [commenthol/date-holidays#41]
Hey everyone, as in moment-holidays (https://github.com/kodie/moment-holiday#isholiday), is it possible to provide a custom holidays-array (or something equal) for check the input-Date.
My use case is to "validate" dates provided by client, so its not always matching with the official dates (sometimes they're open, even if there are holidays)
Or do you have another idea to realize this?

Thanks! Dominik

**Comment by dominikstohl** [comment]
maybe another option: is it possible to get a holiday date by name, so I could i.e. save "Christmas" and can check the date with normal Date-Functions?

**Comment by dominikstohl** [comment]
Is setHoliday() overwriting the existing rules? How can I delete als existing routes and add a set of rules?

**Comment by commenthol** [comment]
Use the parser with your own ruleset. Check the implementation of date-holidays but use your own holidays.json file. That should do the trick.

**Comment by dominikstohl** [comment]
Thanks for providing this awesome tool and your fast help. Your input was very good. :)
