### ISSUE TITLE
Generated files not updated for version `3.21.1`

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [commenthol/date-holidays#421]
I noticed that after updating from version `3.21.0` to version `3.21.1`, our diff was empty, not reflecting the change from https://github.com/commenthol/date-holidays/pull/420.

It looks like only `countries/CA.yaml` was updated in this release.

If I clone the repo and `npm run all` locally I also see updates to the following files:
* `data/holidays.json`
* `src/data.js`
* `lib/data.cjs`
* All the files in `dist/`

Could you have a look? Maybe some steps in the release workflow are happening in the wrong order.

**Comment by commenthol** [comment]
Hi @ehoogeveen-medweb ,

v3.21.2 has been published. This version should contain the required files.
I am sorry that this has happened.
