### ISSUE TITLE
Inconsistencies in classification of Dutch public holidays

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [commenthol/date-holidays#434]
I noticed that Goede vrijdag (Good Friday) is marked as a public holiday, but Bevrijdingsdag (Liberation Day) is not.

Both are official public holidays:
* [Dutch](https://www.rijksoverheid.nl/onderwerpen/arbeidsovereenkomst-en-cao/vraag-en-antwoord/officiele-feestdagen)
* [English](https://www.government.nl/topics/working-hours/question-and-answer/public-holidays-in-the-netherlands)

However, not everyone is entitled to a free day on the following public holidays (unfortunately I think these pages are only available in Dutch):
* [Goede vrijdag (Good Friday)](https://www.rijksoverheid.nl/onderwerpen/arbeidsovereenkomst-en-cao/vraag-en-antwoord/goede-vrijdag-vrije-dag): A regular work day for most people
* [Koningsdag (King’s Day)](https://www.rijksoverheid.nl/onderwerpen/arbeidsovereenkomst-en-cao/vraag-en-antwoord/koningsdag-27-april-vrije-dag): Most people have the day off
* [Bevrijdingsdag (Liberation Day)](https://www.rijksoverheid.nl/onderwerpen/arbeidsovereenkomst-en-cao/vraag-en-antwoord/bevrijdingsdag-5-mei-vrije-dag): It just says to check with your employer
* [Hemelvaartsdag (Ascension Day)](https://www.rijksoverheid.nl/onderwerpen/arbeidsovereenkomst-en-cao/vraag-en-antwoord/hemelvaartsdag-vrije-dag): Most people have the day off
* [Tweede pinksterdag (Whit Monday)](https://www.rijksoverheid.nl/onderwerpen/arbeidsovereenkomst-en-cao/vraag-en-antwoord/is-tweede-pinksterdag-een-vrije-dag): Most people have the day off (but it says to check with your employer)

So I'm not entirely sure how they should be classified within date-holidays, but if Liberation Day is optional then Good Friday should probably be optional as well.

**Comment by commenthol** [comment]
Hi @ehoogeveen-medweb ,

The definitions of holidays can be found in https://github.com/commenthol/date-holidays/blob/master/docs/specification.md#types-of-holidays 

For optional holidays where only "special" groups are entitled to enjoy them, I'd recommend to add a note stating that "constraint".
I'd appreciate if you could file a Pull-Request on the findings you have made.
