### ISSUE TITLE
Suggestion: Add unique ID to each holiday.

### ISSUE THREAD

**Issue by KyleMo** [commenthol/date-holidays#444]
This package is great, thanks. However, it would be very helpful if you could add unique identifiers to each holiday, including for each local. The implementation of this wouldn't be super complicated and wouldn't take any special maintenance. Go through each holiday and update it with a unique string or integer or anything. These never have to be updated again - thats the whole point of an ID for it be consist and unique forever. Theres no reason I can think of that would require you to update the holiday ID ever again once it is created. Even if names change or holidays changes or even date changes, the ID should always stay the same. 

Adding an ID field would add no extra maintenance effort. All the effort would be upfront creating the script. Considering others have requested the same, I really believe its worth doing.

**Comment by commenthol** [comment]
Reading old issues might provide reasonable answers https://github.com/commenthol/date-holidays/issues/10 https://github.com/commenthol/date-holidays/issues/153

**Comment by KyleMo** [comment]
https://www.npmjs.com/package/@kylemonstad/date-holidays-with-ids
