### ISSUE TITLE
Doesn't compile with commonjs

### ISSUE THREAD

**Issue by mswilson4040** [commenthol/date-holidays#45]
I'm using date-holidays in my angular project. Everything works fine but my unit tests all fail after importing it. It looks like date-holidays won't compile with commonjs module:

> Uncaught TypeError: date_holidays_1.default is not a constructor

Here is my tsconig.spec

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "baseUrl": "./",
    "module": "commonjs",  <-- changing so something like "es2015" works fine (but breaks other things not related to date-holdays. I need to keep it as commonjs)
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

**Comment by mswilson4040** [comment]
This is the same error message found in #44 but different issue

**Comment by johnolos** [comment]
I could take a look.

Could you provide a minimalistic repo for me to test out?
As stated in the other issue, for me this works as intended; although I use 'es2015'.

Or even better, if you find the underlying issue, a PR is surely welcome!

**Comment by mswilson4040** [comment]
I upgraded to Angular 7 and this issue has gone away. This version comes with some upgrades to some of the testing dependencies angular uses (Karma/Jasmine) which likely fixed itself. This can be closed.
