### ISSUE TITLE
Security Vulnerability - Prototype Pollution in lodash.pick

### ISSUE THREAD

**Issue by wilhen01** [commenthol/date-holidays#452]
From Dependabot:

> Versions of lodash prior to 4.17.19 are vulnerable to Prototype Pollution. The functions pick, set, setWith, update, updateWith, and zipObjectDeep allow a malicious user to modify the prototype of Object if the property identifiers are user-supplied. Being affected by this issue requires manipulating objects based on user-provided property values or arrays.
>
> This vulnerability causes the addition or modification of an existing property that will exist on all objects and may lead to Denial of Service or Code Execution under specific circumstances.

I think this means you'll need to bring in `lodash` rather than `lodash.pick` since the modularised versions haven't been updated in many years.

**Comment by commenthol** [comment]
Hi @wilhen01 ,
Yes you are right, lodash modularized versions are outdated. PR is on its way.

**Comment by commenthol** [comment]
v3.23.6 was published.
