### ISSUE TITLE
Help with SG Holidays Date

### ISSUE THREAD

**Issue by benkhong** [commenthol/date-holidays#462]
I updated the SG.yaml file to disable 9 April 2024 and enable 10 April 2024 for the Singapore holiday - Hari Raya. 
However, it still shows up as 9 April 2024 even when I updated the package to latest version. 

I believe it has to do with the timezone appended to it => Singapore should be GMT +8 instead of -6. How can I chagne this? "2024-04-10 00:00:00 -0600" - I am unsure why this "-6" timezone issue is only happening with the 2 Hari Raya Holidays in SG. All the other 10 holidays in SG are fine.

What am I missing out here? Please help! Thank you!

**Comment by commenthol** [comment]
See https://github.com/commenthol/date-holidays/blob/master/docs/specification.md#hijra-dates 

> Note: Islamic days start at sunset which depends on latitude/ longitude. To avoid such calculations, the approximation of using 18:00 as hour of sunset is made.

**Comment by benkhong** [comment]
Got it, thanks for the clarification!
