### ISSUE TITLE
HU.yaml - incorrect name of the public holiday 15th March

### ISSUE THREAD

**Issue by humenmar** [commenthol/date-holidays#464]
Hello,

March 15 marks the anniversary of the outbreak of the Hungarian Revolution in **1848**, not 1948 as the name of the holiday suggests here https://github.com/commenthol/date-holidays/blob/master/data/countries/HU.yaml#L31.

Sources:
- https://studyinhungary.hu/living-in-hungary/menu/national-holidays.html
- https://en.wikipedia.org/wiki/Public_holidays_in_Hungary
- https://publicholidays.hu/revolution-day/

**Comment by commenthol** [comment]
@humenmar 
Could you please file a PR with the desired change?
