### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by paulGeoghegan** [commenthol/date-holidays#476]
I've been trying to get the package working with no luck. I'm running BUN 1.1.4 and a Sveltekit app.
I'm just trying to print out the list of Holidays in Ireland for the year. Here is my code:
```
	function getUnavailableDates() {
		let hd = new Holidays();
		hd.init('IE');
		let holidays = hd.getHolidays(2024);
		console.log(holidays);
	}
	getUnavailableDates();
```
Whenever I run this though I'm just getting an empty list back.

**Comment by paulGeoghegan** [comment]
Also I have tried other countries and years but I still get an empty list.

**Comment by commenthol** [comment]
This is a node package. Please use node instead of bun.
