### ISSUE TITLE
Provide better scaling data files

### ISSUE THREAD

**Issue by pke** [commenthol/date-holidays#5]
Thanks for setting up this project!
I'd like to use it but I only need the holidays of a certain set of countries.
The current https://github.com/commenthol/date-holidays/blob/master/data/holidays.json contains all countries/regions and translations.
Since I am aiming to keep my app bundle size at a small size I wonder if we could organize the data json differently? 

While I could implement a pre-build step and remove all the countries not needed I think other users might also gain something if the data could be included more fine grained.

**Comment by commenthol** [comment]
@pke agreed. I am preparing a script right now which allows to pick/ omit the countries you require for a custom build.

**Comment by commenthol** [comment]
v0.1.9 includes the requested - please check the new section in README.md.
