### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by rew62** [commenthol/date-holidays#54]
Would the author consider putting this library on a CDN like cloudflare or https://cdnjs.com so that we can use sites like Codepen to prototype. Thanks in advance.

**Comment by commenthol** [comment]
Please see https://github.com/commenthol/date-holidays#cdn

**Comment by rew62** [comment]
I saw the CDN reference for https://unpkg.com/date-holidays/dist/ in the readme.md, however, I do not see the holidays.json file hosted on the CDN for prototyping.

**Comment by commenthol** [comment]
Sorry but I am confused now. What exactly do you expect from the data file (=holidays.json) alone? 
Btw. you the holidays.json file is on unpkg.

**Comment by rew62** [comment]
Thank you for the response, sorry, I am new! I am trying to prototype date-holidays, and eventually incorporate that with some calendar js. So I have a codepen, and I was able to point to https://unpkg.com/date-holidays@1.3.2/dist/index.min.js, but obviously the js needs the data file. Here is my pen: https://codepen.io/rew222/pen/zyENKP

**Comment by commenthol** [comment]
please use the umd file instead of index.
