### ISSUE TITLE
Filtering by multiple holiday types is not working as expected

### ISSUE THREAD

**Issue by gerryster** [commenthol/date-holidays#56]
Based on the [API documentation](https://github.com/commenthol/date-holidays-parser/blob/master/docs/Holidays.md#holidaysinitcountry-state-region-opts), I was expecting to be able to pass an array of holiday types to Holidays.init and have it return only holidays of those types. For example:

```javascript
const Holidays = require('date-holidays');
const us_all = new Holidays('us');
new Set(us_all.getHolidays(2018).map(h => h.type))
// returns Set { 'public', 'observance', 'optional' } as expected

# filtering by a single type works as expected:
const us_optional = new Holidays('us', {types: ['optional']})
new Set(us_optional.getHolidays(2018).map(h => h.type))
// returns Set { 'optional' }

# But filtering by multiple types returns nothing:
const us_optional_public = new Holidays('us', {types: ['optional', 'public']})
new Set(us_optional_public.getHolidays(2018).map(h => h.type))
// returns Set {} but I am expecting Set{'optional', 'public'}
```

Note that I am running this on Node 10 which has support for the new Set type. I am also running this against master as of 4768392130fb8b349841155fb3333bb1de8c62dc .

I am not sure if this is a documentation bug but it would be nice to be able to filter by multiple types.

**Comment by commenthol** [comment]
Hi @gerryster 
Thanks for rising this issue. Its fixed now with date-holidays-parser@1.2.3.
