### ISSUE TITLE
issue with new years eve

### ISSUE THREAD

**Issue by jamesdixon** [commenthol/date-holidays#65]
Hi there, first, thanks for a great library!

We recently ran into an issue with the range for New Year's Eve showing up properly. Here's the code I'm running:

```js
    // create a new instance of holidays for the business' country
    const holidays = new Holidays(country) // US for this example

    // set timezone for the holidays
    holidays.setTimezone(timezone) // America/Denver for this example

    // get all of the holidays for the current year
    const countryHolidays = holidays.getHolidays('2018')
```

When I log `countryHolidays`, I see the following for New Year's Eve:

```js
{ date: '2018-12-31 18:00:00',
  start: 2019-01-01T01:00:00.000Z,
  end: 2019-01-01T07:00:00.000Z,
  name: 'New Year\'s Eve',
  type: 'observance' }
```

I'd expect `start` to be `2018-12-31T07:00:00.000Z`.

Thoughts? Thanks in advance for your help!

**Comment by commenthol** [comment]
date "2018-12-31 18:00:00" is the local start date and time - given the assumption that Dec. 31 is a working day and New Year's Eve starts at 6:00pm not 0:00am.
Your timezone set is "America/Denver" which is -7h UTC.
Adding 7h to "2018-12-31 18:00:00" gives start "2019-01-01T01:00:00.000Z" which is UTC.

**Comment by jamesdixon** [comment]
Thanks for the clarification! The only thing I would challenge is the assumption. I would argue that even though the name references "eve," I think most observe the entire day as new year's Eve. I'm not finding anything that indicates it starts at 6pm. Thoughts?

**Comment by commenthol** [comment]
in other countries New Year's Eve is a normal working day. Festivities usually start in the evening where shops are closed etc. Don't know how this is handled in the US.

**Comment by jamesdixon** [comment]
It's a working day in the US as well and festivities also start in the evening. That said, I think in general when people speak of a holiday, they speak of it as the entire day. In the case of NYE, people say "tomorrow is NYE" not "tomorrow at 6pm is NYE."

I think I can work around this, but I'm hoping you'll consider the change as it doesn't seem consistent with what's generated by the library for other holidays. For example, Christmas Eve, is output as a full day rather than a specific time.

```js
{ date: '2018-12-24 00:00:00',
    start: 2018-12-24T07:00:00.000Z,
    end: 2018-12-25T07:00:00.000Z,
    name: 'Christmas Eve',
    type: 'optional' }
```

**Comment by commenthol** [comment]
Nothing needs to be graved in stone. If NYE starts at midnight then it should start there. You decide. Just create a PR. Holidays is about humans and their feelings and rites. This project is just a tool.

**Comment by jamesdixon** [comment]
I couldn't agree more 👍  I'll probably just work around it on my end just to ensure I'm not updating data that shouldn't be updated as I can only confidently speak for how this day is observed in the US.

Thanks!
