### ISSUE TITLE
Make holidays.json a compiled asset instead of checked into version control?

### ISSUE THREAD

**Issue by gerryster** [commenthol/date-holidays#69]
_Disclaimer: this is not an issue but a request for comment. However, a Github issue seems like the closest thing to an RFC._

I am wondering if it makes sense to remove data/holidays.json from version control and move the YAML to JSON process into the build process? Specifically, it would mean moving `node scripts/holidays2json.js` into the scripts/build step of package.json. This way, the full holidays.json would be packaged with the node module. It would also line up a bit more closely when [customizing which countries exist in holidays.json](https://github.com/commenthol/date-holidays#custom-builds-of-holidaysjson).

I would also like this from a development standpoint. In the past, I have had merge conflicts with holidays.json which were more of an annoyance as I was able to regenerate the file on my branch.

What do you think?

**Comment by commenthol** [comment]
Hi @gerryster, I agree with your  RFC. Pushing the json file into the build process makes sense. Do you like to prepare a PR?

**Comment by gerryster** [comment]
Sure, I can create a PR.

**Comment by commenthol** [comment]
holidays.json is now a compiled asset.
