### ISSUE TITLE
Falling back to the Calendarific API for missing countries?

### ISSUE THREAD

**Issue by ryan-cal** [commenthol/date-holidays#73]
What are your thoughts about falling back to the [Calendarific Holidays API](https://calendarific.com) for missing countries?

**Comment by commenthol** [comment]
Hi @ryan-cal, please consider the restrictions on the Free Version. https://calendarific.com/#pricing 
To be honest I don't see this API in this library. If you like to rely on this data please consider starting a new project which uses this data and makes a lookup to the REST API for the missing ones.

On the other hand you are invited to contribute here for the countries you are currently missing. Please take a look at the placeholder files in /data/countries/*.todo .
Just take a look at the [spec](https://github.com/commenthol/date-holidays/blob/master/docs/specification.md) and check the other files. More than a editor is not needed.
