### ISSUE TITLE
Add a YAML linter to the build/test process

### ISSUE THREAD

**Issue by gerryster** [commenthol/date-holidays#84]
This is a TODO. I have used the [Python yamllint](https://pypi.org/project/yamllint/) command for this in the past. There is also a [Node tool](https://www.npmjs.com/package/yaml-lint) but I have no experience with it.

**Comment by commenthol** [comment]
Do we really need this? If parsing the YAML to JSON fails then there will always be an immediate exception.
Most problems I experienced with not quoted dates, e.g. 2019-02-18 as those will be parsed into a Date object instead of a string which then is converted to a ISO Date string on JSON output.

**Comment by gerryster** [comment]
I thought of this when reviewing one of the PR's and noticed redundant value quotes were being removed. I have had success in other projects with non-trivial YAML configuration by adding a linter. My biggest motivation in the past was to quickly spot duplicate keys. This project does have robust tests that will should raise issues around duplicate keys. The other benefit is reducing long term git churn as things would become more standardized.

My motivation here is to catch accidents earlier and to push some of the code review responsibility onto the computer. If you want to handle future TODO items in something besides a Github issue, I am fine with that.

**Comment by commenthol** [comment]
eslint-plugin-yml was added in https://github.com/commenthol/date-holidays/tree/e65ebeb65edefa1a22a62ec341bcd78d1f47eee1
