### ISSUE TITLE
Symfony installation

### ISSUE THREAD

**Issue by TELLO0815** [commenthol/date-holidays#97]
Hi there,

sorry im new bee.
Whats the best way to install under Symfony? Just put the folder in my assets or is there a better way?

THX
Mike

**Comment by commenthol** [comment]
Hi @TELLO0815, I am sorry that I can't help you here. This project is based on javascript so in your case you may need to think of using the lib in the browser. 
There is an example within this project which may give you an idea. The README also has a section with CDN. So please take a look there.
