### ISSUE TITLE
Support for Indonesia and Malaysia

### ISSUE THREAD

**Issue by ozsirma** [commenthol/date-holidays#99]
Hi,
If it is possible, I request that Indonesia and Malaysia be added.
Thank you!

**Comment by gerryster** [comment]
Thanks for your feedback. There are several countries which need to be added and good to know that there is interest in Indonesia and Malaysia. Also, pull requests are welcome. See the [contributing guide](https://github.com/commenthol/date-holidays/blob/master/CONTRIBUTING.md) for more information.

**Comment by backtrackbaba** [comment]
@ozsirma Could you share the holiday lists for Indonesia and Malaysia?

**Comment by commenthol** [comment]
Both Indonesia any Malaysia are supported.
